декоративные элементы на главной странице
htmlacademy-htmlcss/1552929-nerds-29 pull request #21
Opened 2020-10-16 17:41 UTC by ADudin

Добавил декоративные элементы на главную страницу. Похоже на макет, но карта в футере отображается немного иначе, наверное в чем-то есть ошибка, но я не смог ее найти. Таблица .levels-container на макете как-то хитро оформлена, я очень долго мучился, но так и не понял как там правильно задать отступы между ячейками, чтобы получилось идентично.

2020-10-17 16:07 UTC, AlexanderGJJ requested changes

2020-10-17 16:07 UTC, AlexanderGJJ commented on css/style.css
> +.service-item:first-child::before {
У тебя сейчас дублируются стили для всех элементов, попробуй вынеси повторяющиеся стили в отдельный селектор, а через nth-child будет меняться только фоновое изображение

2020-10-17 16:07 UTC, AlexanderGJJ commented on css/style.css
> +    transform: translate(0, 11px);
Если задать позиционирование относительно li дотаточно только top указать, трансформации не нужны

2020-10-17 16:07 UTC, AlexanderGJJ commented on css/style.css
>  .adress-container {
Для этого блока можно общие паддинги внутри задать, чтобы не делать отступ на каждом дочернем элементе этого блока

2020-10-17 16:11 UTC, AlexanderGJJ requested changes

2020-10-17 16:11 UTC, AlexanderGJJ commented on css/style.css
> +    margin: 63px 0px 0px 0px;
Отступ можно сдлелать за счет родительского блока, так же как у тебя сделаны горизонтальные отступы сейчас и нижний вертикальный

2020-10-17 16:11 UTC, AlexanderGJJ commented on index.html
> +        <p class="popup-header">Напишите нам</p>
Можно использовать заголовок тут, вместо p

2020-10-18 11:42 UTC, ADudin commented on css/style.css
> +    opacity: 0.2;
Похоже я где-то накосячил с размерами, но не смог понять где, поэтому чтобы футер не уезжал, я немного изменил отступы в этом блоке. Добавил flex-wrap, теперь должно пройти проверку переполнения контентом.

2020-10-18 19:52 UTC, merged